try {
    let x = noExiste()
} catch(err) {
    console.log(err)
}
